---
title: "Plotting"
output: html_notebook
---

```{r}
topBillCanceled <- billCanceled %>%
  group_by(badgeNumber) %>%
  nest() %>%
  slice(1:5) %>%
  unnest()
```

```{r}
aTopBillCanceled <- topBillCanceled %>%
  gather(
    key = "axis", value = "value", "regRead", "consFinal"
  )
```

```{r}
labels = list(
  "regRead" = "End of month meter read (g)",
  "consFinal" = "Consumption (g)"
)

plot_labeller <- function(variable, value){
  if (value == "regRead") {
    return(labels[value])
  } else if (value == "consFinal") {
    return(labels[value])
  } else {
    return(as.character(value))
  }
}

aTopBillCanceled %>%
  group_by(badgeNumber) %>%
  do(
    plot = ggplot(data = .) +
      aes(x = readDate, y = value) +
      facet_grid(
        rows = vars(axis), scale = "free",
        labeller = plot_labeller
      ) +
      geom_line(data = . %>% filter(axis == "consFinal"), stat = "identity") +
      geom_bar(data = . %>% filter(axis == "regRead"), stat = "identity") +
      ggtitle(.$badgeNumber),
    save = ggsave(
      filename = paste0(.$badgeNumber, ".png"),
      path = cancelPlotDir,
      device = "png"
    )
  )
```

```{r}
do(
  plot = ggplot(data = .) + 
    aes(x = date, y = as.numeric(value)) + 
    facet_grid(
      rows = vars(axis), scale = "free",
      labeller = plot_labeller
    ) +
    geom_bar(data = . %>% filter(axis == "endRead_g"), stat = "identity") +
    geom_line(data = . %>% filter(axis == "volume_kg"), stat = "identity") +
    ggtitle(.$source),
    save = ggsave(filename = paste0(.$source, "_Monthly.png"), path = outputDir, device = "png")
  )
```
